### ISSUE TITLE
Relax upper bound on `bifunctors`?

### ISSUE THREAD

**Issue by typedrat** [reinerp/indexed-extras#5]
It is not currently usable with the latest Stackage LTS versions without fudging stuff because of the `bifunctors < 5.4` requirement.

**Comment by NicolasT** [comment]
Yes please. As an alternative, any chance this Hackage curators (ping @cartazio) could bump this on Hackage?

**Comment by cartazio** [comment]
Could you open a trustees issue ticket please?
